version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/clojure:openjdk-11-lein-2.9.1-stretch
    steps:
      - checkout
      - restore_cache:
          key: slackbot-clj-v0-{{ checksum "project.clj" }}
      - run: |
          curl -s https://raw.githubusercontent.com/borkdude/clj-kondo/master/script/install-clj-kondo | bash
      - run: lein deps
      - save_cache:
          paths:
            - ~/.m2
            - /usr/local/bin/clj-kondo
          key: slackbot-clj-v0-{{ checksum "project.clj" }}
      - run: |
          make lint test
          lein uberjar
          # lein nvd check
